BanSachWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ban_sach.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult MainContent()
        {
            ViewBag.Message = "MainContent";
            return View();
        }
        public ActionResult Error()
        {
            return View();
        }
    }
}

BanSachWeb/Controllers/SachController.cs
using BanSachWeb.Models;
using BanSachWeb.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using System.Data.Entity;
namespace BanSachWeb.Controllers
{
    public class SachController : Controller
    {
        // GET: Sach
        QuanLyBanSachModel db=new QuanLyBanSachModel();
        
        public IQueryable<BookViewModel> GetBookQuery()
        {
            return db.Saches.AsNoTracking()
                .Select(s => new BookViewModel
                {
                    MaSach=s.MaSach,
                    TenSach=s.TenSach,
                    SoLuongDaBan=s.SoLuongDaBan,
                    AnhSach=s.AnhSach,
                    GiaBan=s.GiaBan,
                    GiaGoc=s.GiaGoc
                });
        }
        public IQueryable<BookViewModel> GetTopBookQuery(int amount=13)
        {
            
            return db.Saches.AsNoTracking()
                .Select(s => new BookViewModel
                {
                    MaSach = s.MaSach,
                    TenSach = s.TenSach,
                    SoLuongDaBan = s.SoLuongDaBan,
                    AnhSach = s.AnhSach,
                    GiaBan = s.GiaBan,
                    GiaGoc = s.GiaGoc
                }).OrderByDescending(s=>s.SoLuongDaBan).Take(amount);
        }
        public IQueryable<BookViewModel> GetSearchedBookQuery(List<Sach> sachs)
        {
            return sachs.Select(s => new BookViewModel
            {
                MaSach = s.MaSach,
                TenSach= s.TenSach,
                SoLuongDaBan = s.SoLuongDaBan,
                AnhSach = s.AnhSach,
                GiaBan = s.GiaBan,
                GiaGoc = s.GiaGoc
            }).AsQueryable();
        }
        
        public ActionResult Index(int? page)
        {
            ViewBag.Title = "Sách";
            ViewBag.nameAction = "Index";
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            var products = GetBookQuery().OrderBy(s => s.MaSach).ToPagedList(pageNumber, pageSize);
            return View("Index",products);
        }
        

        public ActionResult SachDetail(int id)
        {
            // Assuming you have a DbContext called 'db'
            var sach = db.Saches.Include(s => s.TacGias).FirstOrDefault(s => s.MaSach == id);


            if (sach == null)
                {
                    // Handle case where book with the given ID is not found
                    return HttpNotFound(); // Or any other appropriate action, such as redirecting to an error page
                }

                return View(sach); // Pass the retrieved book object to the view
        }
        public ActionResult TopSale(int? page)
        {
            int pageNumber = (page ?? 1);
            int pageSize = 10;
            var topBooks = GetTopBookQuery().ToPagedList(pageNumber, pageSize);
            ViewBag.Title = "Sách bán chạy";
            ViewBag.nameAction = "TopSale";
            return View("Index",topBooks);
        }
        public PartialViewResult TopSalePartial()
        {
            var topSaleBooks = GetTopBookQuery(4);
            return PartialView("_TopSale", topSaleBooks);
        }
        public ActionResult Search(SearchViewModel model, int? page)
        {
            var sachViewModelList = db.Saches.Include(s => s.TacGias)
                .Where(s => string.IsNullOrEmpty(model.SearchKey) ||
                            s.TacGias.Any(a => a.TenTacGia.Contains(model.SearchKey) || s.TenSach.Contains(model.SearchKey)))
                .Select(s => new BookViewModel
                {
                    MaSach = s.MaSach,
                    TenSach = s.TenSach,
                    SoLuongDaBan = s.SoLuongDaBan,
                    AnhSach = s.AnhSach,
                    GiaBan = s.GiaBan,
                    GiaGoc = s.GiaGoc
                    // Map other properties here if necessary
                }).ToList();

            // Convert SachViewModel to Sach if necessary
            model.BooksResult = sachViewModelList.Select(s => new Sach
            {
                MaSach = s.MaSach,
                TenSach = s.TenSach,
                SoLuongDaBan = s.SoLuongDaBan,
                AnhSach = s.AnhSach,
                GiaBan = s.GiaBan,
                GiaGoc = s.GiaGoc
                // Map other properties here if necessary
            }).ToList();

            ViewBag.Title = "Sách";
            ViewBag.nameAction = "Search";

            int pageSize = 10;
            int pageNumber = (page ?? 1);
            var book = GetSearchedBookQuery(model.BooksResult).ToPagedList(pageNumber, pageSize);

            return View("Index", book);
        }

    }



}

BanSachWeb/Views/Home/MainContent.cshtml
@model IEnumerable<BanSachWeb.Models.BookViewModel>
@{
    ViewBag.Title = "MainContent";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="~/Content/HomeStyle.css" />
</head>

<body>
    <section class="Main_content my-3">
        <div class="container">
            <div class="slider">
                <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
                    <div class="carousel-indicators">
                        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
                        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
                    </div>
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            <img src="~/Image/wallpaperflare.com_wallpaper (1).jpg" class="d-block w-100" alt="...">
                        </div>
                        <div class="carousel-item">
                            <img src="~/Image/8d0375e692893dd76498.jpg" class="d-block w-100" alt="...">
                        </div>
                        <div class="carousel-item">
                            <img src="~/Image/womanyellingcat-1573233850.jpg" class="d-block w-100" alt="...">
                        </div>
                    </div>
                    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Previous</span>
                    </button>
                    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Next</span>
                    </button>
                </div>
            </div>
        </div>
    </section>
    <section>
        @Html.Action("TopSalePartial","Sach")
    </section>
    
</body>

</html>